/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import List.ListCtPhieuthue;
import List.ListDia;
import List.ListTradia;
import Thucthe.Dia;
import Thucthe.GetDataDia;
import Thucthe.CtPhieuThue;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nhat
 */
public class FormTradia extends javax.swing.JPanel {
    FormDia frmdia;
    ListCtPhieuthue listCtPhieuthue = new ListCtPhieuthue();
    public static  PreparedStatement ps = null;
    public static String  sqlCtPhieuthue = "select soPhieu,maDia,soLuongThue,giathue,tinhtrang from CtPhieuthue order by soPhieu asc";
    String maDia1;
    String tenDia;
    String tinhTrang1;
    int soLuongTon;
    String hangSx;
    int giaThue;
    
    Date hanTra1;
    

    /**
     * Creates new form FormTradia
     */
    Date ngayTra = new Date(System.currentTimeMillis());
    ListTradia listtradia=new ListTradia();
    double thanhTien = 0;
    public FormTradia() {
        initComponents();
        UpdateTable.LoadData(sqlCtPhieuthue, tblCtPhieuthue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCtPhieuthue = new javax.swing.JTable();
        btnTradia = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtSrchCtPhieuthue = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnTinhTien = new javax.swing.JButton();
        lblThongbaoQuahan = new javax.swing.JLabel();
        lblThanhtien = new javax.swing.JLabel();
        lbltongthanhtien = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMaPhieu = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2), "Danh sách chi tiết phiếu thuê", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(102, 0, 102))); // NOI18N

        tblCtPhieuthue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu thuê", "Mã đĩa", "Số lượng", "Giá thuê", "Thành tiền"
            }
        ));
        tblCtPhieuthue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCtPhieuthueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCtPhieuthue);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnTradia.setBackground(new java.awt.Color(102, 0, 102));
        btnTradia.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnTradia.setForeground(new java.awt.Color(255, 255, 255));
        btnTradia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_return_24px.png"))); // NOI18N
        btnTradia.setText("Trả đĩa");
        btnTradia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTradiaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(102, 0, 102));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_delete_24px.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTim.setBackground(new java.awt.Color(102, 0, 102));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnTinhTien.setBackground(new java.awt.Color(102, 0, 102));
        btnTinhTien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTinhTien.setForeground(new java.awt.Color(255, 255, 255));
        btnTinhTien.setText("Tính tiền");
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });

        lblThanhtien.setBackground(new java.awt.Color(102, 0, 102));
        lblThanhtien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblThanhtien.setForeground(new java.awt.Color(102, 0, 102));
        lblThanhtien.setText("Thành tiền:");

        jLabel1.setText("Mã phiếu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSrchCtPhieuthue, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThongbaoQuahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnTradia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnTinhTien))
                                            .addGap(18, 18, 18)
                                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblThanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbltongthanhtien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 21, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSrchCtPhieuthue)
                    .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblThongbaoQuahan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltongthanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(201, 201, 201)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTradia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTradiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTradiaActionPerformed
        // TODO add your handling code here:
        int row = tblCtPhieuthue.getSelectedRow();
        
        if(row>=0){
            int soLuongThue = (int) tblCtPhieuthue.getValueAt(row, 2);
            String soPhieu = (String) tblCtPhieuthue.getValueAt(row, 0);
            String tinhtrg = (String) tblCtPhieuthue.getValueAt(row, 4);
            String maDia = (String) tblCtPhieuthue.getValueAt(row, 1);
            String tinhTrang = "Đã trả";
            int tt = soLuongThue*giaThue;
            CtPhieuThue ctpt = new CtPhieuThue(soPhieu, maDia, soLuongThue, giaThue, tinhTrang);
            try {
                if(listtradia.updatetinhtrang(tinhTrang,soPhieu,maDia) && tinhtrg.equalsIgnoreCase("Chưa trả")){
                    int updateslt2 = soLuongTon + soLuongThue;
                    listCtPhieuthue.UpdateSltDia2(maDia,updateslt2);
                    try {
                        listtradia.updatengaykhachhangdentrathanhtien(soPhieu,maDia,ngayTra,(int) thanhTien);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "Lưu ngày khách đến trả thất bại");
                    }
                    JOptionPane.showMessageDialog(this, "Trả đĩa thành công");
                }else{
                    JOptionPane.showMessageDialog(this, "Đĩa này đã được khách trả!");
                    
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Không Lưu vào được tình trạng");
            }
          
            //int updateslt2 = soLuongTon + soLuongThue;
            //Dia d = new Dia(maDia, tenDia, tinhTrang, updateslt2, hangSx, giaThue);
            //
            //this.btnTim.doClick();
             UpdateTable.LoadData(sqlCtPhieuthue, tblCtPhieuthue);
           
            
        }
        
        
        
        
        
    }//GEN-LAST:event_btnTradiaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = tblCtPhieuthue.getSelectedRow();
        if(row>=0){
            String soPhieu = (String) tblCtPhieuthue.getValueAt(row, 0);
            if(listCtPhieuthue.delete(soPhieu)){
                JOptionPane.showMessageDialog(this, "Xoá thành công");
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra");
                this.btnTim.doClick();
        }
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        if(this.txtSrchCtPhieuthue.getText().length() == 0){
            String sqll = "select soPhieu,maDia,soLuongThue,giathue,tinhtrang from CtPhieuthue order by soPhieu asc";
            UpdateTable.LoadData(sqll, tblCtPhieuthue);
        }else{
            String sqll = "Select soPhieu,maDia,soLuongThue,giathue,tinhtrang from CtPhieuthue where soPhieu like N'%"+this.txtSrchCtPhieuthue.getText()+"%' "
            + "or maDia like N'%"+this.txtSrchCtPhieuthue.getText()+"%'"
            + "or soLuongThue like N'%"+this.txtSrchCtPhieuthue.getText()+"%'"
            + "or tinhtrang like N'%"+this.txtSrchCtPhieuthue.getText()+"%'"
            + "or giaThue like N'%"+this.txtSrchCtPhieuthue.getText()+"%'";
            UpdateTable.LoadData(sqll, tblCtPhieuthue);
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void tblCtPhieuthueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCtPhieuthueMouseClicked
        // TODO add your handling code here:
        try {
            int row = this.tblCtPhieuthue.getSelectedRow();
            String IDrow = (this.tblCtPhieuthue.getModel().getValueAt(row, 1)).toString();
            String IDrow2 = (this.tblCtPhieuthue.getModel().getValueAt(row, 0)).toString();
            String sqll = "Select * from Dia where maDia = '"+IDrow+"'";
            String sql2 = "Select hanTra from Phieuthue where soPhieu = '"+IDrow2+"'";
            String sql3 = "Select * from Phieuthue where soPhieu = '"+IDrow2+"'";
            ResultSet rs = UpdateTable.ShowTextField(sqll);
            ResultSet rs2 = UpdateTable.ShowTextField(sql2);
            ResultSet rs3 = UpdateTable.ShowTextField(sql3);
            hanTra1=(Date) listtradia.ngaykhachhangdentratrongphieuthue(IDrow2);
            soLuongTon=listtradia.soluongton(IDrow);
            
            if(rs.next() && rs3.next()){
                this.txtMaPhieu.setText(rs3.getString("SoPhieu"));
                maDia1 = rs.getString("maDia");
                tenDia = rs.getString("tenDia");
                tinhTrang1 = rs.getString("tinhTrang");
                hangSx = rs.getString("hangSx");
                giaThue = rs.getInt("giaThue");
            }
            
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_tblCtPhieuthueMouseClicked

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed
        
        int row = this.tblCtPhieuthue.getSelectedRow();
        int soLuongThue = (int) this.tblCtPhieuthue.getValueAt(row, 2);
        int giaThue = (int) tblCtPhieuthue.getValueAt(row, 3);
        
        DecimalFormat df = new DecimalFormat("###,###,###.## VND");
        //System.out.println(ngayTra);
       // System.out.println(hanTra1);
        if(ngayTra.compareTo(hanTra1)>0){
            String quaHan = "Đĩa trả quá hạn, phạt 50% tiền thuê";
            lblThongbaoQuahan.setText(quaHan);
            thanhTien = soLuongThue*giaThue + 0.5*soLuongThue*giaThue;
            lbltongthanhtien.setText(df.format(thanhTien));
        }
        else{
            lblThongbaoQuahan.setText("");
            thanhTien = soLuongThue*giaThue;
            lbltongthanhtien.setText(df.format(thanhTien));
        }
        
    }//GEN-LAST:event_btnTinhTienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    public javax.swing.JButton btnTinhTien;
    private javax.swing.JButton btnTradia;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblThanhtien;
    private javax.swing.JLabel lblThongbaoQuahan;
    private javax.swing.JLabel lbltongthanhtien;
    public javax.swing.JTable tblCtPhieuthue;
    private javax.swing.JTextField txtMaPhieu;
    private javax.swing.JTextField txtSrchCtPhieuthue;
    // End of variables declaration//GEN-END:variables
}
