/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import List.ListNhanvien;
import Thucthe.Nhanvien;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Nhat
 */
public class FormNhanvien extends javax.swing.JPanel {
    
    ListNhanvien listNhanvien = new ListNhanvien();
    public static  PreparedStatement ps = null;
    public static String  sqlNhanvien = "select * from Nhanvien order by maNhanvien asc";

    /**
     * Creates new form FormNhanvien
     */
    public FormNhanvien() {
        initComponents();
        UpdateTable.LoadData(sqlNhanvien, tblNhanvien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDsNhanvien = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanvien = new javax.swing.JTable();
        pnlTtNhanvien = new javax.swing.JPanel();
        lblTenNhanvien = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblMaNhanvien = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblSoDT = new javax.swing.JLabel();
        txtMaNhanvien = new javax.swing.JTextField();
        txtTenNhanvien = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        cbbGioiTinh = new javax.swing.JComboBox<>();
        lblSrchNhanvien = new javax.swing.JLabel();
        txtSrchNhanvien = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        pnlDsNhanvien.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2), "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(102, 0, 102))); // NOI18N

        tblNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Địa chỉ", "Số điện thoại", "Giới tính", "Mật khẩu"
            }
        ));
        tblNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanvien);

        javax.swing.GroupLayout pnlDsNhanvienLayout = new javax.swing.GroupLayout(pnlDsNhanvien);
        pnlDsNhanvien.setLayout(pnlDsNhanvienLayout);
        pnlDsNhanvienLayout.setHorizontalGroup(
            pnlDsNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDsNhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDsNhanvienLayout.setVerticalGroup(
            pnlDsNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDsNhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlTtNhanvien.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2), "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(102, 0, 102))); // NOI18N

        lblTenNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTenNhanvien.setForeground(new java.awt.Color(102, 0, 102));
        lblTenNhanvien.setText("Tên nhân viên:");

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGioiTinh.setForeground(new java.awt.Color(102, 0, 102));
        lblGioiTinh.setText("Giới tính:");

        lblMaNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblMaNhanvien.setForeground(new java.awt.Color(102, 0, 102));
        lblMaNhanvien.setText("Mã nhân viên:");

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDiaChi.setForeground(new java.awt.Color(102, 0, 102));
        lblDiaChi.setText("Địa chỉ:");

        lblSoDT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSoDT.setForeground(new java.awt.Color(102, 0, 102));
        lblSoDT.setText("Số điện thoại:");

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        javax.swing.GroupLayout pnlTtNhanvienLayout = new javax.swing.GroupLayout(pnlTtNhanvien);
        pnlTtNhanvien.setLayout(pnlTtNhanvienLayout);
        pnlTtNhanvienLayout.setHorizontalGroup(
            pnlTtNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTtNhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTtNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTtNhanvienLayout.createSequentialGroup()
                        .addComponent(lblMaNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                    .addGroup(pnlTtNhanvienLayout.createSequentialGroup()
                        .addComponent(lblTenNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenNhanvien))
                    .addGroup(pnlTtNhanvienLayout.createSequentialGroup()
                        .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDiaChi))
                    .addGroup(pnlTtNhanvienLayout.createSequentialGroup()
                        .addComponent(lblSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoDT))
                    .addGroup(pnlTtNhanvienLayout.createSequentialGroup()
                        .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbbGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTtNhanvienLayout.setVerticalGroup(
            pnlTtNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTtNhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTtNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lblMaNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlTtNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlTtNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlTtNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSoDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSoDT, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlTtNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(cbbGioiTinh))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        lblSrchNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSrchNhanvien.setForeground(new java.awt.Color(102, 0, 102));
        lblSrchNhanvien.setText("Tên nhân viên:");

        btnTim.setBackground(new java.awt.Color(102, 0, 102));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTim.setForeground(new java.awt.Color(204, 204, 204));
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_search_24px.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(102, 0, 102));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThem.setForeground(new java.awt.Color(204, 204, 204));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_add_24px.png"))); // NOI18N
        btnThem.setText("Nhập mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(102, 0, 102));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(204, 204, 204));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_save_close_24px.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(102, 0, 102));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSua.setForeground(new java.awt.Color(204, 204, 204));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_approve_and_update_24px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(102, 0, 102));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(204, 204, 204));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_delete_24px.png"))); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDsNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(pnlTtNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblSrchNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSrchNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTtNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSrchNhanvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                .addComponent(lblSrchNhanvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnTim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(104, 104, 104))
                    .addComponent(pnlDsNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(this.txtMaNhanvien.getText().equals("") || this.txtTenNhanvien.getText().equals("") || this.txtDiaChi.getText().equals("") || this.txtSoDT.getText().equals("") || this.cbbGioiTinh.getSelectedItem().equals(""))
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin");
        else if(this.txtMaNhanvien.getText().matches("^NV([0-9][0-9])$") == false)
            JOptionPane.showMessageDialog(this, "Mã nhân viên theo dạng NVxx");
        else if(this.txtTenNhanvien.getText().matches("^[a-zA-Z_ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶ\" + \"ẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợ\" +\"ụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\\\s]+$") == false)
            JOptionPane.showMessageDialog(this, "Tên không chứa ký tự đặc biệt");
        else if(this.txtDiaChi.getText().matches("^[a-z0-9A-Z_ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶ+ẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợ+ụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\s]+$") == false)
            JOptionPane.showMessageDialog(this, "Địa chỉ không chứa ký tự đặc biệt");
        else if(this.txtSoDT.getText().matches("\\d{10}") == false)
            JOptionPane.showMessageDialog(this, "Số điện thoại gồm 10 số");
        
        else{
            Nhanvien nv = new Nhanvien(this.txtMaNhanvien.getText(), this.txtTenNhanvien.getText(), this.txtDiaChi.getText(), this.txtSoDT.getText() ,this.cbbGioiTinh.getSelectedItem().toString());
            ListNhanvien.InsertNhanvien(nv);
            this.btnTim.doClick();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if(this.txtMaNhanvien.getText().equals("") || this.txtTenNhanvien.getText().equals("") || this.txtDiaChi.getText().equals("") || this.txtSoDT.getText().equals("") || this.cbbGioiTinh.getSelectedItem().equals(""))
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin");
        else if(this.txtMaNhanvien.getText().matches("^NV([0-9][0-9])$") == false)
            JOptionPane.showMessageDialog(this, "Mã thành viên theo dạng NVxx");
        else if(this.txtTenNhanvien.getText().matches("^[a-zA-Z_ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶ\" + \"ẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợ\" +\"ụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\\\s]+$") == false)
            JOptionPane.showMessageDialog(this, "Tên không chứa ký tự đặc biệt");
        else if(this.txtDiaChi.getText().matches("^[a-z0-9A-Z_ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶ+ẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợ+ụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\s]+$") == false)
            JOptionPane.showMessageDialog(this, "Địa chỉ không chứa ký tự đặc biệt");
        else if(this.txtSoDT.getText().matches("\\d{10}") == false)
            JOptionPane.showMessageDialog(this, "Số điện thoại gồm 10 số");
        
        else{
            Nhanvien nv = new Nhanvien(this.txtMaNhanvien.getText(), this.txtTenNhanvien.getText(), this.txtDiaChi.getText(), this.txtSoDT.getText() ,this.cbbGioiTinh.getSelectedItem().toString());
            if(listNhanvien.UpdateNhanvien(nv)){
                JOptionPane.showMessageDialog(this, "Sửa thành công");
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra");
                this.btnTim.doClick();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(this.txtMaNhanvien.getText().equals("") || this.txtTenNhanvien.getText().equals("") || this.txtDiaChi.getText().equals("") || this.txtSoDT.getText().equals("") || this.cbbGioiTinh.getSelectedItem().equals("") )
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin");
        else{
            Nhanvien nv = new Nhanvien(this.txtMaNhanvien.getText(), this.txtTenNhanvien.getText(), this.txtDiaChi.getText(), this.txtSoDT.getText() ,this.cbbGioiTinh.getSelectedItem().toString());
            if(listNhanvien.DeleteNhanvien(this.txtMaNhanvien.getText())){
                JOptionPane.showMessageDialog(this, "Xoá thành công");
            }else
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra");
                this.btnTim.doClick();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanvienMouseClicked
        // TODO add your handling code here:
        try {
            int row = this.tblNhanvien.getSelectedRow();
            String IDrow = (this.tblNhanvien.getModel().getValueAt(row, 0)).toString();
            String sqll = "Select * from Nhanvien where maNhanvien = '"+IDrow+"'";
            ResultSet rs = UpdateTable.ShowTextField(sqll);
            if(rs.next()){
                this.txtMaNhanvien.setText(rs.getString("maNhanvien"));
                this.txtTenNhanvien.setText(rs.getString("tenNhanvien"));
                this.txtDiaChi.setText(rs.getString("diaChi"));
                this.txtSoDT.setText(rs.getString("soDT"));
                this.cbbGioiTinh.setSelectedItem(rs.getString("gioiTinh"));
                
                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblNhanvienMouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        if(this.txtSrchNhanvien.getText().length() == 0){
            String sqll = "Select * from Nhanvien";
            UpdateTable.LoadData(sqll, tblNhanvien);
        }else{
            String sqll = "Select * from Nhanvien where maNhanvien like N'%"+this.txtSrchNhanvien.getText()+"%' "
            + "or tenNhanvien like N'%"+this.txtSrchNhanvien.getText()+"%'"
            + "or diaChi like N'%"+this.txtSrchNhanvien.getText()+"%'"
            + "or gioiTinh like N'%"+this.txtSrchNhanvien.getText()+"%'";
            UpdateTable.LoadData(sqll, tblNhanvien);
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.txtMaNhanvien.setText(null);
        this.txtTenNhanvien.setText(null);
        this.txtDiaChi.setText(null);
        this.txtSoDT.setText(null);
        
        txtMaNhanvien.requestFocus();
    }//GEN-LAST:event_btnThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbGioiTinh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblMaNhanvien;
    private javax.swing.JLabel lblSoDT;
    private javax.swing.JLabel lblSrchNhanvien;
    private javax.swing.JLabel lblTenNhanvien;
    private javax.swing.JPanel pnlDsNhanvien;
    private javax.swing.JPanel pnlTtNhanvien;
    private javax.swing.JTable tblNhanvien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNhanvien;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtSrchNhanvien;
    private javax.swing.JTextField txtTenNhanvien;
    // End of variables declaration//GEN-END:variables
}
