/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import java.awt.CardLayout;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Nhat
 */

public class FormMain extends javax.swing.JFrame {
    FormDia pGDDia;
    FormThanhvien pGDThanhvien;
    FormNhanvien pGDNhanvien;
    FormPhieuthue pGDPhieuthue;

    FormTradia pGDTradia;
    FormThongkeDoanhThu pGDThongke;
    SearchDia pGDSearchDia;
    SearchThanhvien pGDSearchThanhvien;
    SearchNhanvien pGDSearchNhanvien;
    FormTaikhoan pGDTaikhoan;
    FormThongkeKhachHang pGDThongkeKhachHang;
    FormThongkeDia pGDThongkeDia;
    FormTheLoai1 pGDTheLoai;
    CardLayout cardLayout;

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        cardLayout = new CardLayout();
        pnlCard.setLayout(cardLayout);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mnMenuBar = new javax.swing.JMenuBar();
        mnTaikhoan = new javax.swing.JMenu();
        btnDangxuat = new javax.swing.JMenuItem();
        mnAccounts = new javax.swing.JMenu();
        btnDia = new javax.swing.JMenuItem();
        btnThanhvien = new javax.swing.JMenuItem();
        btnNhanvien = new javax.swing.JMenuItem();
        btnTaikhoan = new javax.swing.JMenuItem();
        btnTheLoai = new javax.swing.JMenuItem();
        mnXuly = new javax.swing.JMenu();
        btnPhieuthue = new javax.swing.JMenuItem();
        btnTradia = new javax.swing.JMenuItem();
        mnThongke = new javax.swing.JMenu();
        btnThongkeDoanhthu = new javax.swing.JMenuItem();
        btnThongkeDia = new javax.swing.JMenuItem();
        btnThongkeKhachhang = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btnSearchDia = new javax.swing.JMenuItem();
        btnSearchThanhvien = new javax.swing.JMenuItem();
        btnSearchNhanvien = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCard.setBackground(new java.awt.Color(255, 255, 255));
        pnlCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(136, 68, 96));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_dvd_logo_80px.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ CHO THUÊ BĂNG ĐĨA");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(271, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );

        pnlCard.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1310, 450));

        getContentPane().add(pnlCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1310, 600));

        mnMenuBar.setBackground(new java.awt.Color(102, 0, 102));
        mnMenuBar.setForeground(new java.awt.Color(255, 255, 255));

        mnTaikhoan.setForeground(new java.awt.Color(102, 0, 102));
        mnTaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_user_male_circle_filled_50px_1.png"))); // NOI18N
        mnTaikhoan.setText("TÀI KHOẢN");
        mnTaikhoan.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        btnDangxuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangxuat.setForeground(new java.awt.Color(102, 0, 102));
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_login_rounded_right_24px.png"))); // NOI18N
        btnDangxuat.setText("ĐĂNG XUẤT");
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });
        mnTaikhoan.add(btnDangxuat);

        mnMenuBar.add(mnTaikhoan);

        mnAccounts.setBackground(new java.awt.Color(102, 0, 102));
        mnAccounts.setForeground(new java.awt.Color(102, 0, 102));
        mnAccounts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_management_filled_50px_2.png"))); // NOI18N
        mnAccounts.setText("QUẢN LÝ");
        mnAccounts.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        btnDia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDia.setForeground(new java.awt.Color(102, 0, 102));
        btnDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_cd_24px_1_1.png"))); // NOI18N
        btnDia.setText("QUẢN LÝ ĐĨA");
        btnDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDiaMousePressed(evt);
            }
        });
        mnAccounts.add(btnDia);

        btnThanhvien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThanhvien.setForeground(new java.awt.Color(102, 0, 102));
        btnThanhvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_user_male_circle_24px.png"))); // NOI18N
        btnThanhvien.setText("QUẢN LÝ THÀNH VIÊN");
        btnThanhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThanhvienMousePressed(evt);
            }
        });
        mnAccounts.add(btnThanhvien);

        btnNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNhanvien.setForeground(new java.awt.Color(102, 0, 102));
        btnNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_employee_card_24px.png"))); // NOI18N
        btnNhanvien.setText("QUÀN LÝ NHÂN VIÊN");
        btnNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNhanvienMousePressed(evt);
            }
        });
        mnAccounts.add(btnNhanvien);

        btnTaikhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTaikhoan.setForeground(new java.awt.Color(102, 0, 102));
        btnTaikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_contacts_24px.png"))); // NOI18N
        btnTaikhoan.setText("QUẢN LÝ TÀI KHOẢN");
        btnTaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTaikhoanMousePressed(evt);
            }
        });
        mnAccounts.add(btnTaikhoan);

        btnTheLoai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTheLoai.setForeground(new java.awt.Color(102, 0, 102));
        btnTheLoai.setText("QUẢN LÝ THỂ LOẠI");
        btnTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTheLoaiMousePressed(evt);
            }
        });
        mnAccounts.add(btnTheLoai);

        mnMenuBar.add(mnAccounts);

        mnXuly.setForeground(new java.awt.Color(102, 0, 102));
        mnXuly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_services_filled_50px.png"))); // NOI18N
        mnXuly.setText("XỬ LÝ");
        mnXuly.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        btnPhieuthue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPhieuthue.setForeground(new java.awt.Color(102, 0, 102));
        btnPhieuthue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_agreement_24px.png"))); // NOI18N
        btnPhieuthue.setText("LẬP PHIẾU THUÊ");
        btnPhieuthue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPhieuthueMousePressed(evt);
            }
        });
        mnXuly.add(btnPhieuthue);

        btnTradia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTradia.setForeground(new java.awt.Color(102, 0, 102));
        btnTradia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_assignment_return_24px.png"))); // NOI18N
        btnTradia.setText("TRẢ ĐĨA");
        btnTradia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTradiaMousePressed(evt);
            }
        });
        btnTradia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTradiaActionPerformed(evt);
            }
        });
        mnXuly.add(btnTradia);

        mnMenuBar.add(mnXuly);

        mnThongke.setForeground(new java.awt.Color(102, 0, 102));
        mnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_statistics_30px_1.png"))); // NOI18N
        mnThongke.setText("THỐNG KÊ");
        mnThongke.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        btnThongkeDoanhthu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThongkeDoanhthu.setForeground(new java.awt.Color(102, 0, 102));
        btnThongkeDoanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_graph_report_24px.png"))); // NOI18N
        btnThongkeDoanhthu.setText("THỐNG KÊ DOANH THU");
        btnThongkeDoanhthu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThongkeDoanhthuMousePressed(evt);
            }
        });
        btnThongkeDoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeDoanhthuActionPerformed(evt);
            }
        });
        mnThongke.add(btnThongkeDoanhthu);

        btnThongkeDia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThongkeDia.setForeground(new java.awt.Color(102, 0, 102));
        btnThongkeDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_graph_report_24px.png"))); // NOI18N
        btnThongkeDia.setText("THỐNG KÊ ĐĨA");
        btnThongkeDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThongkeDiaMousePressed(evt);
            }
        });
        btnThongkeDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeDiaActionPerformed(evt);
            }
        });
        mnThongke.add(btnThongkeDia);

        btnThongkeKhachhang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThongkeKhachhang.setForeground(new java.awt.Color(102, 0, 102));
        btnThongkeKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_graph_report_24px.png"))); // NOI18N
        btnThongkeKhachhang.setText("THỐNG KÊ KHÁCH HÀNG");
        btnThongkeKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThongkeKhachhangMousePressed(evt);
            }
        });
        mnThongke.add(btnThongkeKhachhang);

        mnMenuBar.add(mnThongke);

        jMenu1.setForeground(new java.awt.Color(102, 0, 102));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_search_folder_48px.png"))); // NOI18N
        jMenu1.setText("TÌM KIẾM");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        btnSearchDia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchDia.setForeground(new java.awt.Color(102, 0, 102));
        btnSearchDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_search_more_24px.png"))); // NOI18N
        btnSearchDia.setText("TÌM KIẾM ĐĨA");
        btnSearchDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSearchDiaMousePressed(evt);
            }
        });
        btnSearchDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDiaActionPerformed(evt);
            }
        });
        jMenu1.add(btnSearchDia);

        btnSearchThanhvien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchThanhvien.setForeground(new java.awt.Color(102, 0, 102));
        btnSearchThanhvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_search_more_24px.png"))); // NOI18N
        btnSearchThanhvien.setText("TÌM KIẾM THÀNH VIÊN");
        btnSearchThanhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSearchThanhvienMousePressed(evt);
            }
        });
        jMenu1.add(btnSearchThanhvien);

        btnSearchNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchNhanvien.setForeground(new java.awt.Color(102, 0, 102));
        btnSearchNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_search_more_24px.png"))); // NOI18N
        btnSearchNhanvien.setText("TÌM KIẾM NHÂN VIÊN");
        btnSearchNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSearchNhanvienMousePressed(evt);
            }
        });
        jMenu1.add(btnSearchNhanvien);

        mnMenuBar.add(jMenu1);

        setJMenuBar(mnMenuBar);

        setSize(new java.awt.Dimension(1328, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnDiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiaMousePressed
        // TODO add your handling code here:
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        pGDDia = new FormDia();       
        pnlCard.add(pGDDia, "1");
        cardLayout.show(pnlCard,"1");
        
    }//GEN-LAST:event_btnDiaMousePressed

    private void btnThanhvienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThanhvienMousePressed
        // TODO add your handling code here:
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        pGDThanhvien = new FormThanhvien();       
        pnlCard.add(pGDThanhvien, "2");
        cardLayout.show(pnlCard,"2");
    }//GEN-LAST:event_btnThanhvienMousePressed

    private void btnNhanvienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanvienMousePressed
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        pGDNhanvien = new FormNhanvien();       
        pnlCard.add(pGDNhanvien, "3");
        cardLayout.show(pnlCard,"3");
    }//GEN-LAST:event_btnNhanvienMousePressed

    private void btnPhieuthueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhieuthueMousePressed
        // TODO add your handling code here:
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        pGDPhieuthue = new FormPhieuthue();       
        pnlCard.add(pGDPhieuthue, "4");
        cardLayout.show(pnlCard,"4");
    }//GEN-LAST:event_btnPhieuthueMousePressed

    private void btnTradiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTradiaMousePressed
        // TODO add your handling code here:
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        pGDTradia = new FormTradia();       
        pnlCard.add(pGDTradia, "6");
        cardLayout.show(pnlCard,"6");
    }//GEN-LAST:event_btnTradiaMousePressed

    private void btnThongkeDoanhthuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeDoanhthuMousePressed
        // TODO add your handling code here:
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        try {       
            pGDThongke = new FormThongkeDoanhThu();
        } catch (SQLException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnlCard.add(pGDThongke, "7");
        cardLayout.show(pnlCard,"7");
    }//GEN-LAST:event_btnThongkeDoanhthuMousePressed

    private void btnTradiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTradiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTradiaActionPerformed

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        // TODO add your handling code here:
        FormDangNhap fdn = new FormDangNhap();
        fdn.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void btnSearchDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchDiaActionPerformed

    private void btnSearchDiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchDiaMousePressed
        // TODO add your handling code here:
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        pGDSearchDia = new SearchDia();       
        pnlCard.add(pGDSearchDia, "8");
        cardLayout.show(pnlCard,"8");
    }//GEN-LAST:event_btnSearchDiaMousePressed

    private void btnSearchThanhvienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchThanhvienMousePressed
        // TODO add your handling code here:
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        pGDSearchThanhvien = new SearchThanhvien();       
        pnlCard.add(pGDSearchThanhvien, "9");
        cardLayout.show(pnlCard,"9");
    }//GEN-LAST:event_btnSearchThanhvienMousePressed

    private void btnSearchNhanvienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchNhanvienMousePressed
        // TODO add your handling code here:
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        pGDSearchNhanvien = new SearchNhanvien();       
        pnlCard.add(pGDSearchNhanvien, "9");
        cardLayout.show(pnlCard,"9");
    }//GEN-LAST:event_btnSearchNhanvienMousePressed

    private void btnTaikhoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaikhoanMousePressed
        // TODO add your handling code here:
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        pGDTaikhoan = new FormTaikhoan();       
        pnlCard.add(pGDTaikhoan, "10");
        cardLayout.show(pnlCard,"10");
    }//GEN-LAST:event_btnTaikhoanMousePressed

    private void btnThongkeDiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeDiaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongkeDiaMousePressed

    private void btnThongkeKhachhangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeKhachhangMousePressed
        // TODO add your handling code here:
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        try {       
            pGDThongkeKhachHang = new FormThongkeKhachHang();
        } catch (SQLException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnlCard.add(pGDThongkeKhachHang, "11");
        cardLayout.show(pnlCard,"11");
    }//GEN-LAST:event_btnThongkeKhachhangMousePressed

    private void btnThongkeDoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeDoanhthuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongkeDoanhthuActionPerformed

    private void btnThongkeDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeDiaActionPerformed
        // TODO add your handling code here:
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        try {       
            pGDThongkeDia = new FormThongkeDia();
        } catch (SQLException ex) {
            Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnlCard.add(pGDThongkeDia, "12");
        cardLayout.show(pnlCard,"12");
    }//GEN-LAST:event_btnThongkeDiaActionPerformed

    private void btnTheLoaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTheLoaiMousePressed
        // TODO add your handling code here:
        pnlCard.removeAll();
        pnlCard.repaint();
        pnlCard.revalidate();
        pGDTheLoai = new FormTheLoai1();       
        pnlCard.add(pGDTheLoai, "15");
        cardLayout.show(pnlCard,"15");
        
    }//GEN-LAST:event_btnTheLoaiMousePressed
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(114,64,114));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(68,5,68));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }
    
    public void AssignMenu(String role){
        if(role.equals("quanly")){
            mnXuly.setVisible(false);
            mnThongke.setVisible(false);
            btnDia.setVisible(false);
            btnThanhvien.setVisible(false);
        }
        if(role.equals("nhanvien")){
            btnNhanvien.setVisible(false);
            btnTaikhoan.setVisible(false);
            btnSearchNhanvien.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnDangxuat;
    public javax.swing.JMenuItem btnDia;
    public javax.swing.JMenuItem btnNhanvien;
    private javax.swing.JMenuItem btnPhieuthue;
    private javax.swing.JMenuItem btnSearchDia;
    private javax.swing.JMenuItem btnSearchNhanvien;
    private javax.swing.JMenuItem btnSearchThanhvien;
    private javax.swing.JMenuItem btnTaikhoan;
    public javax.swing.JMenuItem btnThanhvien;
    private javax.swing.JMenuItem btnTheLoai;
    private javax.swing.JMenuItem btnThongkeDia;
    private javax.swing.JMenuItem btnThongkeDoanhthu;
    private javax.swing.JMenuItem btnThongkeKhachhang;
    private javax.swing.JMenuItem btnTradia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenu mnAccounts;
    public javax.swing.JMenuBar mnMenuBar;
    public javax.swing.JMenu mnTaikhoan;
    public javax.swing.JMenu mnThongke;
    public javax.swing.JMenu mnXuly;
    private javax.swing.JPanel pnlCard;
    // End of variables declaration//GEN-END:variables

    
}
