/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import static Giaodien.FormDia.sqlDia;
import List.ListDia;
import java.sql.PreparedStatement;
import Thucthe.Dia;
import java.sql.PreparedStatement;

/**
 *
 * @author Nhat
 */
public class SearchDia extends javax.swing.JPanel {
    ListDia listDia = new ListDia();
    public static  PreparedStatement ps = null;
    public static String  sqlDia = "select * from Dia order by maDia asc";

    /**
     * Creates new form SearchDia
     */
    public SearchDia() {
        initComponents();
        UpdateTable.LoadData(sqlDia, tblDia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDsDia = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDia = new javax.swing.JTable();
        lblSearchDia = new javax.swing.JLabel();
        txtSearchDia = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();

        pnlDsDia.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2), "Danh sách đĩa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(102, 0, 102))); // NOI18N

        tblDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đĩa", "Tên đĩa", "Tình trạng", "số lượng tồn", "Hãng SX", "Giá thuê"
            }
        ));
        jScrollPane1.setViewportView(tblDia);

        javax.swing.GroupLayout pnlDsDiaLayout = new javax.swing.GroupLayout(pnlDsDia);
        pnlDsDia.setLayout(pnlDsDiaLayout);
        pnlDsDiaLayout.setHorizontalGroup(
            pnlDsDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDsDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDsDiaLayout.setVerticalGroup(
            pnlDsDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDsDiaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblSearchDia.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSearchDia.setForeground(new java.awt.Color(102, 0, 102));
        lblSearchDia.setText("Tên đĩa hoặc thể loại:");

        btnTim.setBackground(new java.awt.Color(102, 0, 102));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTim.setForeground(new java.awt.Color(204, 204, 204));
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_search_24px.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(lblSearchDia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchDia, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(449, 449, 449))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlDsDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblSearchDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearchDia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTim)))
                .addGap(554, 554, 554))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(85, Short.MAX_VALUE)
                    .addComponent(pnlDsDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        if(this.txtSearchDia.getText().length() == 0){
            String sqll = "Select * from Dia";
            UpdateTable.LoadData(sqll, tblDia);
        }else{
            String sqll = "Select * from Dia where maDia like N'%"+this.txtSearchDia.getText()+"%' "
            + "or tenDia like N'%"+this.txtSearchDia.getText()+"%'"
            + "or hangSx like N'%"+this.txtSearchDia.getText()+"%'"
            + "or tinhTrang like N'%"+this.txtSearchDia.getText()+"%'";
            UpdateTable.LoadData(sqll, tblDia);
        }
    }//GEN-LAST:event_btnTimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearchDia;
    private javax.swing.JPanel pnlDsDia;
    public javax.swing.JTable tblDia;
    private javax.swing.JTextField txtSearchDia;
    // End of variables declaration//GEN-END:variables
}
