/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import static Giaodien.FormNhanvien.sqlNhanvien;
import List.ListNhanvien;
import java.sql.PreparedStatement;

/**
 *
 * @author Nhat
 */
public class SearchNhanvien extends javax.swing.JPanel {
    ListNhanvien listNhanvien = new ListNhanvien();
    public static  PreparedStatement ps = null;
    public static String  sqlNhanvien = "select * from Nhanvien order by maNhanvien asc";

    /**
     * Creates new form SearchNhanvien
     */
    public SearchNhanvien() {
        initComponents();
        UpdateTable.LoadData(sqlNhanvien, tblNhanvien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDsNhanvien = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanvien = new javax.swing.JTable();
        txtSrchNhanvien = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        lblSrchNhanvien = new javax.swing.JLabel();

        pnlDsNhanvien.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2), "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(102, 0, 102))); // NOI18N

        tblNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Địa chỉ", "Số điện thoại", "Giới tính", "Mật khẩu"
            }
        ));
        jScrollPane1.setViewportView(tblNhanvien);

        javax.swing.GroupLayout pnlDsNhanvienLayout = new javax.swing.GroupLayout(pnlDsNhanvien);
        pnlDsNhanvien.setLayout(pnlDsNhanvienLayout);
        pnlDsNhanvienLayout.setHorizontalGroup(
            pnlDsNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDsNhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDsNhanvienLayout.setVerticalGroup(
            pnlDsNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDsNhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnTim.setBackground(new java.awt.Color(102, 0, 102));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTim.setForeground(new java.awt.Color(204, 204, 204));
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_search_24px.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        lblSrchNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSrchNhanvien.setForeground(new java.awt.Color(102, 0, 102));
        lblSrchNhanvien.setText("Tên nhân viên hoặc SĐT:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lblSrchNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSrchNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(597, 597, 597))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlDsNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSrchNhanvien)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTim)
                        .addComponent(lblSrchNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(554, 554, 554))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addComponent(pnlDsNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        if(this.txtSrchNhanvien.getText().length() == 0){
            String sqll = "Select * from Nhanvien";
            UpdateTable.LoadData(sqll, tblNhanvien);
        }else{
            String sqll = "Select * from Nhanvien where maNhanvien like N'%"+this.txtSrchNhanvien.getText()+"%' "
            + "or tenNhanvien like N'%"+this.txtSrchNhanvien.getText()+"%'"
            + "or diaChi like N'%"+this.txtSrchNhanvien.getText()+"%'"
            + "or gioiTinh like N'%"+this.txtSrchNhanvien.getText()+"%'";
            UpdateTable.LoadData(sqll, tblNhanvien);
        }
    }//GEN-LAST:event_btnTimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSrchNhanvien;
    private javax.swing.JPanel pnlDsNhanvien;
    private javax.swing.JTable tblNhanvien;
    private javax.swing.JTextField txtSrchNhanvien;
    // End of variables declaration//GEN-END:variables
}
