/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;

import List.ListThanhvien;
import java.sql.PreparedStatement;
import Thucthe.Thanhvien;
import Thucthe.GetDataThanhvien;

/**
 *
 * @author Nhat
 */
public class viewThanhvien extends javax.swing.JFrame {
    
    ListThanhvien listThanhvien = new ListThanhvien();
    public static  PreparedStatement ps = null;
    public static String  sqlThanhvien = "select * from Thanhvien order by maThanhvien asc";

    /**
     * Creates new form viewThanhvien
     */
    public viewThanhvien() {
        initComponents();
        UpdateTable.LoadData(sqlThanhvien, tblThanhvien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDsThanhvien = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThanhvien = new javax.swing.JTable();
        txtSrchThanhvien = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnChon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlDsThanhvien.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2), "Danh sách thành viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(102, 0, 102))); // NOI18N

        tblThanhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thành viên", "Tên thành viên", "Địa chỉ", "Số điện thoại", "Ngày hết hạn", "Số CMND"
            }
        ));
        tblThanhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThanhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThanhvien);

        javax.swing.GroupLayout pnlDsThanhvienLayout = new javax.swing.GroupLayout(pnlDsThanhvien);
        pnlDsThanhvien.setLayout(pnlDsThanhvienLayout);
        pnlDsThanhvienLayout.setHorizontalGroup(
            pnlDsThanhvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDsThanhvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDsThanhvienLayout.setVerticalGroup(
            pnlDsThanhvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        btnTim.setBackground(new java.awt.Color(102, 0, 102));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_search_24px.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.setActionCommand("");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnChon.setBackground(new java.awt.Color(102, 0, 102));
        btnChon.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnChon.setForeground(new java.awt.Color(255, 255, 255));
        btnChon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/icons8_checkmark_24px.png"))); // NOI18N
        btnChon.setText("Chọn");
        btnChon.setActionCommand("");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSrchThanhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlDsThanhvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(btnChon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSrchThanhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDsThanhvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77))
        );

        setSize(new java.awt.Dimension(693, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblThanhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThanhvienMouseClicked
       
        
    }//GEN-LAST:event_tblThanhvienMouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        if(this.txtSrchThanhvien.getText().length() == 0){
            String sqll = "Select * from Thanhvien";
            UpdateTable.LoadData(sqll, tblThanhvien);
        }else{
            String sqll = "Select * from Thanhvien where maThanhvien like N'%"+this.txtSrchThanhvien.getText()+"%' "
            + "or tenThanhvien like N'%"+this.txtSrchThanhvien.getText()+"%'"
            + "or diaChi like N'%"+this.txtSrchThanhvien.getText()+"%'"
            + "or cMND like N'%"+this.txtSrchThanhvien.getText()+"%'";
            UpdateTable.LoadData(sqll, tblThanhvien);
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:
        int row = tblThanhvien.getSelectedRow();
        GetDataThanhvien.setMaThanhvien(tblThanhvien.getValueAt(row,0).toString());
        FormPhieuthue.GetDataIntoTbl();
        setVisible(false);
        
    }//GEN-LAST:event_btnChonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewThanhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewThanhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewThanhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewThanhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewThanhvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnTim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDsThanhvien;
    private javax.swing.JTable tblThanhvien;
    private javax.swing.JTextField txtSrchThanhvien;
    // End of variables declaration//GEN-END:variables
}
